apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42
  labels:
    app: will42
spec:
  replicas: 4
  selector:
    matchLabels:
      app: will42
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
      - name: will42
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: service-will42
spec:
  selector:
    app : will42
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
